<?php

namespace Modules\Backend\Models;

use Illuminate\Database\Eloquent\Model;

class ShippingFee extends Model
{
    public const EGYPT_CITIES = [
        '10th of Ramadan',
        '15th of May',
        '6th of October',
        'Abnub',
        'Abu Hammad',
        'Abu Kabir',
        'Abu Qurqas',
        'Abu Simbel',
        'Aga',
        'Agami',
        'Akhmim',
        'Alamein',
        'Alexandria',
        'Arish',
        'Ashmoun',
        'Aswan',
        'Asyut',
        'Atfih',
        'Awsim',
        'Badr',
        'Baltim',
        'Banha',
        'Basyoun',
        'Beba',
        'Belbeis',
        'Beni Mazar',
        'Beni Suef',
        'Beni Ubaid',
        'Bilqas',
        'Borg El Arab',
        'Cairo',
        'Dahab',
        'Dairut',
        'Damanhur',
        'Damietta',
        'Dar El Salam',
        'Daraw',
        'Deir Mawas',
        'Dekernes',
        'Desouk',
        'Dikirnis',
        'Dishna',
        'Diyarb Negm',
        'Duweiqa',
        'Edfu',
        'Edku',
        'El Badari',
        'El Bagour',
        'El Bayadiya',
        'El Fashn',
        'El Gamaliya',
        'El Ghanayem',
        'El Hamool',
        'El Husseiniya',
        'El Ibrahimiya',
        'El Kanayat',
        'El Khanka',
        'El Mahmoudiyah',
        'El Mahalla El Kubra',
        'El Manzala',
        'El Matareya',
        'El Qanater El Khayreya',
        'El Qantara',
        'El Quseir',
        'El Rahmaniya',
        'El Reyad',
        'El Sadat',
        'El Senbellawein',
        'El Shorouk',
        'El Tor',
        'Esna',
        'Faiyum',
        'Faqous',
        'Faraskur',
        'Farshut',
        'Fayed',
        'Fuwwah',
        'Girga',
        'Giza',
        'Hihya',
        'Hurghada',
        'Ismailia',
        'Itaay El Baroud',
        'Itay El Barud',
        'Juhayna',
        'Kafr El Dawwar',
        'Kafr El Sheikh',
        'Kafr Saad',
        'Kafr Shukr',
        'Kom Hamada',
        'Kom Ombo',
        'Luxor',
        'Madinaty',
        'Mallawi',
        'Mansoura',
        'Manfalut',
        'Manzala',
        'Marsa Alam',
        'Marsa Matruh',
        'Mashtool El Souk',
        'Matay',
        'Menouf',
        'Mersa Matruh',
        'Minya',
        'Minya El Qamh',
        'Mit Ghamr',
        'Mit Salsil',
        'Nag Hammadi',
        'Nasr City',
        'New Administrative Capital',
        'New Alamein',
        'New Aswan',
        'New Beni Suef',
        'New Cairo',
        'New Damietta',
        'New Minya',
        'New Salhia',
        'New Sohag',
        'Nuweiba',
        'Obour',
        'Port Fouad',
        'Port Said',
        'Qaha',
        'Qalyub',
        'Qena',
        'Qift',
        'Quesna',
        'Rafah',
        'Ras El Bar',
        'Ras Gharib',
        'Rosetta',
        'Sadat City',
        'Safaga',
        'Saint Catherine',
        'Samalut',
        'Samannoud',
        'Sahel Selim',
        'Shebin El Kom',
        'Sheikh Zuweid',
        'Sherbin',
        'Shibin El Qanater',
        'Sharm El Sheikh',
        'Shubra El Kheima',
        'Sidi Barrani',
        'Sidi Salem',
        'Siwa',
        'Sohag',
        'Suez',
        'Taba',
        'Tala',
        'Talkha',
        'Tanta',
        'Tahta',
        'Toukh',
        'Wadi El Natrun',
        'Zagazig',
        'Zefta',
    ];

    protected $fillable = [
        'city',
        'amount',
    ];

    protected $casts = [
        'amount' => 'decimal:2',
    ];

    public static function egyptCities(): array
    {
        return self::EGYPT_CITIES;
    }
}
